# ----------- default settings ----------- #
name: Backend card template
description: Used for functional/mechanical issues, as well as development issues.
title: "[Backend]: "
labels: [Backend ⚙️]
# ----------- optional setting ----------- #
# ----------- automatically assigns someone each time an issue is created ----------- #
# assignees:
#    - <insert assignee(s) here>

body:
- type: markdown
  attributes:
    value: |
      Thank you for making time to fill this form!
      Only fill this form if you're 100% sure you can describe it down below.

- type: checkboxes
  attributes:
    label: Prerequisites
    description: Please make sure you have read and completed all the following.
    options:
      - label: I have read the [Contributing Guidelines](https://github.com/nergster/fossy/blob/main/CONTRIBUTING.md).
        required: true
      - label: I agree to follow the [Code of Conduct](https://github.com/nergster/fossy/blob/main/CODE_OF_CONDUCT.md).
        required: true
      - label: Are you intending to include tests?
        required: false

- type: textarea
  attributes:
    label: Summary
    description: Please provide a brief description of the feature.
    placeholder: |
      Example: "section b have outdated links that don't work"
  validations:
    required: true

- type: textarea
  attributes:
    label: Potential Solution
    description: Explain in brief how you intend to tackle the issue.
    placeholder: |
      example: "add updated links to section b"
  validations:
    required: true

- type: dropdown
  attributes:
    label: In which category does the issue belong?
    description: Pick one that describe the issue.
    multiple: false
    options:
      - Docs 📝 - Changes to the documentation only.
      - Feature 🆕 - A new feature.
      - Style 🖌️ - Changes to formatting. (e.g. spreading lines, tabbing, keyword casing...)
      - Test ☑️ - Adding/correcting existing tests.
      - Refactor 🧮 - Restructuring of the code without changing functionality
      - Bugfix 🩹 - A bug fix.
      - Chore 🧹 - Routine maintenance. (e.g. bump version, update changelog or deps).
      - Meta 👨‍💻 - Changes development files, but not product code (e.g. changes to .gitignore, workflows, readme...).
  validations:
    required: true
