blank_issues_enabled: false
contact_links:
  - name: Contributing Guidelines
    url: https://github.com/nergster/fossy/blob/main/CONTRIBUTING.md
    about: This page contains documentation on how to contribute to this repository.